### ISSUE TITLE
Issue related to change email address 

### ISSUE THREAD

**Issue by maysamsameer** [RachelXur/GamiSE_NG#1]
pre-condition: for all different type of users (admin, IT, normal users)

Scenario: when a user wants to change his or her email address, the current email that is logged in will be removed and replaced by the new email  without notification after click update, then the user can use Gamise normally, until he or she logout then old email address will not be able to log in with and user log in with the new email address.

post-condition:
1.System does not notify the user that by changing the email, the current email will be removed permanently and replaced by the email.
2. The new email address gets no notification that it has been added and used in Gamise.
3. Changing the email address with another email address, it is a hazardous sometimes, in case the password has been hacked then the hacker can change the email address of the genuine user and their self the access to the website and the real user will no be able to return to the system.

**Comment by RachelXur** [comment]
Update:
When the user changes the email address or username, the platform will send a " profile updated " email to the old email and the new email. But the user will keep logging into the system. Change email address and username will not log out this user.

**Comment by maysamsameer** [comment]
pre-condition: new registered users (IT and normal users)
scenario: users update the email address
post condition: users receive a notification emails one on the old email and one on the new registered email , notifying the user that the profile has been updated, if not the user then can contact the support.
The fore mentioned issue has been solved.
