### ISSUE TITLE
Gamise Platform-User Update password

### ISSUE THREAD

**Issue by maysamsameer** [RachelXur/GamiSE_NG#10]
**pre-condition**: normal users
**scenario:** user clicks on (Hello,username -> change password) and wants to update the current password .
**post-condition:**
- when user type current and the new password, it is visible by default and there is no possible option to make it invisible.
- system does not object that the new chosen password is same as the old password - no password specification.
-

**Comment by RachelXur** [comment]
Open this issue on GM platform

**Comment by RachelXur** [comment]
Open this issue on GM platform
