### ISSUE TITLE
New Registered users needs a default photo

### ISSUE THREAD

**Issue by maysamsameer** [RachelXur/GamiSE_NG#2]
pre-condition: new registered users (IT and normal users)
scenario: when a new user registered to the website and log in , the user photo will appear as broken link, until the user change the photo, the user photo will continue to appear as broken link when send report , share experience unless it is updated and choose a photo.
post condition: a broken link might be confusing for a first time user of the website, choosing a default photo for all the user which can be changed later according to their preference.

**Comment by RachelXur** [comment]
Update:
Change the default photo of the user. All the users can see the default picture now.

**Comment by maysamsameer** [comment]
pre-condition: new registered users (IT and normal users)
scenario:  new user registered to the website and log in to his or her profile.
post condition: the update of default photo appears and properly was created for the first time registered user, and the forementioned  issue has been solved.
