### ISSUE TITLE
Image URL does not function properly

### ISSUE THREAD

**Issue by maysamsameer** [RachelXur/GamiSE_NG#3]
pre-condition: admin user , IT user and normal user
Scenario: when admin share news and tips , it is required to add a photo URL when fill the related form , when add the url from computer of from google , and update the form, the news are sent to users but photos do not appear when they receive the news email.
post condition: 
adding photo url to the news can be optional to the admin.

**Comment by RachelXur** [comment]
Update:
change the Image URL to optional input. All the users should add our platform email address to their trust list. Then the hyperlink should work and not be blocked.

**Comment by maysamsameer** [comment]
pre-condition: admin users
scenario: admin sends daily news and tips 
post condition: adding photos has been changed to optional , but there is admin users still can't add photo when send daily news and tips.

**Comment by RachelXur** [comment]
Could you explain more about this issue? The admin can only add the image URL from online news or articles. They can't add photo from local.

**Comment by maysamsameer** [comment]
i tried to add photo Url and it appeared in the received emails on inbox , after adding gamise as contact , therefore users should be advised after registration to add gamise as contact , then the issue has been solved.

**Comment by RachelXur** [comment]
Yes, they will be noticed when they get the evaluation notification.
