### ISSUE TITLE
Daily news and Tips email issue

### ISSUE THREAD

**Issue by maysamsameer** [RachelXur/GamiSE_NG#4]
**Pre-condition:** normal users
**Scenario:** received daily news and tips sent by admin to the users reached to the spam folder of (protonmail) mail server, also the (read more) link , was unclickable on (hotmail) mail server but it reached to inbox not in the spam folder.

**Post condition:**
Hotmail user can not follow the daily news and tips sent by the admin, Note that protonmail mail server users when receives the news in the spam, it **does not** show any notification at the top of the email saying it is malicious activity.

**Comment by ebinsaad** [comment]
@maysamsameer very good

**Comment by RachelXur** [comment]
Update:
change the Image URL to optional input. All the users should add our platform email address to their trust list. Then the hyperlink should work and not be blocked.

**Comment by maysamsameer** [comment]
Pre-condition: normal users
Scenario: 1. admin send a daily news to normal users and IT users
2. admin sends tips to normal users and IT
Post condition:
here is the following result of the test of the received emails locations
   -Inbox folder:  uwindsor email server , gmail email server.
   -Spam folder: hotmail (IT user) , and protonmail server
