### ISSUE TITLE
More than one Users Conflict when Report Phishing

### ISSUE THREAD

**Issue by maysamsameer** [RachelXur/GamiSE_NG#6]
pre-condition: more than one user using the same electronic device.
scenario: when clicking to report phishing by a normal user ( i tried first hotmail user) then i reported the issue, then i clicked report from the gmail users, the same page of hotmail user popped up with the same current user's name and when clicked report issue it did not work.

post condition: when a user is currently user signed on , there must be another copy of the website pop up for the new user so they can report the issue safely and no conflict would happen.

**Comment by RachelXur** [comment]
Solved. All the links in the daily email are unique. When users use the same device, they will be no conflict now.

**Comment by maysamsameer** [comment]
**pre-condition**: general users
**scenario:** two users using the same electronic device and one user's account is active and second user tries to launch his or her account.
**post condition**: second users will be directed to login page when there is another user account still logged in. the forementioned issue has been solved.
