### ISSUE TITLE
Unable to delete IT user

### ISSUE THREAD

**Issue by maysamsameer** [RachelXur/GamiSE_NG#7]
**Pre-condition:** IT users and admin
**Scenario:** trying to withdraw an IT user with a more than 1 post on his or her profile.
**Post-condition:** if the IT user has a post then withdrawing it causes an Internal server error, when the IT user delete the post then the IT user is removed.

**Comment by RachelXur** [comment]
Update:
Solved. It should work now. But only the admin can withdrawal the IT department users.

**Comment by maysamsameer** [comment]
Pre-condition: IT users and admin
Scenario: deleting IT user with related posts on gamise
Post-condition: IT user can be removed even if user has post , the forementioned issue has been solved.
