### ISSUE TITLE
Admin user background clickable

### ISSUE THREAD

**Issue by maysamsameer** [RachelXur/GamiSE_NG#8]
**Pre-condition:** Admin users.
**Scenario:** when admin user log in the background around the daily news button and background around daily tips also clickable.
**Post condition:** it is little bit confusing for users if they clicked on the mouse by mistake and it takes them to the news or tips and for future updates of the system , when having links, other button, menus or list all could cause complications in the system.

**Comment by RachelXur** [comment]
Update:
Solved.

**Comment by maysamsameer** [comment]
Pre-condition: Admin users.
Scenario: when admin user log in the background around the daily news button and background around daily tips also clickable.
Post condition: Only the buttons of daily news and tips now are clickable , issue has been solved
