### ISSUE TITLE
Gamise platform-Gamification/add points and achievement 

### ISSUE THREAD

**Issue by maysamsameer** [RachelXur/GamiSE_NG#9]
pre-condition: admin user
scenario: when adding points and achievement points and title and description , users have no limit of how much text can type in,  admin user also has not limit of how much digits can add to the points, admin tries to create new badge and rewards in the Gamification.
post condition: 
- adding multiple lines of text do not wrap and cause the text to appear on very long line on the screen.
- adding points more 9 digits cause the system crashing (Internal server error).
- creating new badge and rewards without adding an image will cause (Internal server error) .

**Comment by RachelXur** [comment]
Open this issue on GM platform
